sudo: required
language: python
python:
  - "3.6"

before_script:
  - export CI_COMMIT_ID=$(git log --format="%H" -n 1)
  - export commit=$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_ID | cut -f1 -d"/" | head -n -1)

script:
  - wget https://raw.githubusercontent.com/shreejoy/OTA/master/new.py
  - wget https://raw.githubusercontent.com/shreejoy/OTA/master/requirements.txt
  - pip3 install -r requirements.txt 
  - python3.6 new.py
  
notifications:
  email:
    on_success: never
    on_failure: always
