sudo: required
language: python
python:
  - "3.6"

before_install:
 - |
   if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.txt)'
   then
     echo "Not running CI since code were not changed."
     exit
   fi
script:
  - wget $flash
  - wget $clone
  - bash clone.sh
  - bash flash.sh
  
notifications:
  email:
    on_success: never
    on_failure: always
